### ISSUE TITLE
Adicionar no final de cada day, dicas sobre a certificação CKA e CKAD

### ISSUE THREAD

**Issue by badtuxx** [badtuxx/DescomplicandoKubernetes#12]

**Comment by marcelofreire1988** [comment]
@badtuxx , como serão essas dicas?

Seria tipo "Treine bastante isso e aquilo?"

**Comment by badtuxx** [comment]
Acho que seria interessante colocar algo: Conteúdo exigido no exame. Algo assim. :)

**Comment by marcelofreire1988** [comment]
Show! Vamo providênciar isso :)

**Comment by marcelofreire1988** [comment]
Fiz aqui referente ao ETCD. Mas não sei se quebra as regras da CNCF. Posso solicitar o PR para revisão.

**Comment by badtuxx** [comment]
Acho que não podemos falar sobre as questões especificamente. Porém falar que determinado tópico é cobrado, eu não vejo problema não. Como por exemplo, Entender e conhecer os procedimentos de backup e restore do etcd são importantes para o exame.
