### ISSUE TITLE
Ebook

### ISSUE THREAD

**Issue by igordrnobrega** [badtuxx/DescomplicandoKubernetes#120]
Hey todos,
eu gerei um eBook do conteudo disponivel aqui. 
Eu tenho minhas dúvidas sobre o quão interessante e, também, da opnião dos autores sobre essa iniciativa. Se todos os autores concordarem e não infrigir nenhum termo legal, posso criar um Pull Request com o projeto para se gerar o arquivo epub aqui nesse repositório.

WDYT?

**Comment by LuanFMelo** [comment]
Será que o repo está maduro o suficiente para gerar um e-book ? Ou acha que isso pode ser resolvido nas próximas versões do e-book ?

**Comment by igordrnobrega** [comment]
Minha Idea é manter um projeto que gere o ebook automaticamente com apenas una linha de código, ou seja, versões/edições podem ser geradas com o mínimo de esforço possível. Além de que quanto antes vermos como ficará o ebook gerado antes podemos definir regras de formatação e padrão para o markdown do conteúdos e gerar o ebook na melhor formatação possível.
E, por exemplo, eu acho muito mais fácil ler todo esse conteúdo em um dispositivo que privilegia a leitura. Ou seja, gero meu ebook e envio para meu dispositivo para que o possa ler a qualquer momento.

**Comment by badtuxx** [comment]
Boaaa!
Mas eu acho bom esperar um pouco. Vamos ter a release 1.0 em breve. :)

**Comment by SpockCoding** [comment]
E aí, em 1 ano o que rolou ? tem o ebook ? Live long and prosper
