### ISSUE TITLE
Adicionar conteúdo sobre os operators

### ISSUE THREAD

**Issue by badtuxx** [badtuxx/DescomplicandoKubernetes#13]

**Comment by fao89** [comment]
Eu to começando a estudar operators e tenho alguns links sobre, infelizmente são em inglês:

- Livro de operators tá sendo disponibilizado de graça:
https://www.redhat.com/cms/managed-files/cl-oreilly-kubernetes-operators-ebook-f21452-202001-en_2.pdf

- Aqui tem uma lista de exercicios:
http://workshop.coreostrain.me/exercises/

- Operator Lifecycle Book:
https://operator-framework.github.io/olm-book/
