### ISSUE TITLE
Dia 4 - Ajustar comando

### ISSUE THREAD

**Issue by adamobuccianti-ext** [badtuxx/DescomplicandoKubernetes#132]
Jeferson, 
na criação do usuário para o K8S, o comando abaixo não localiza o arquivo .key (DIA 4)

Existe algum passo anterior ?

Agora setando as confs de user e key:

kubectl config set-credentials linuxtips --client-certificate=linuxtips.crt --client-key=linuxtips.key --embed-certs --kubeconfig=linuxtips-config

**Comment by zilmarr** [comment]
Salve @adamobuccianti-ext !
Vc precisa criar um CSR e aprovar a sua emissão no cluster. Logo no início [aqui](https://github.com/badtuxx/DescomplicandoKubernetes/blob/master/day-4/DescomplicandoKubernetes-Day4.md#criando-um-usu%C3%A1rio-no-kubernetes) tem o passo a passo. 
Vc deve executar o comando `kubectl config set-credentials linuxtips --client-certificate=linuxtips.crt --client-key=linuxtips.key --embed-certs --kubeconfig=linuxtips-config` na pasta onde se encontram os arquivos do certificado, ou passar o caminho nas chaves correspondentes.
