### ISSUE TITLE
Adicionar conteúdo sobre StatefulSets

### ISSUE THREAD

**Issue by badtuxx** [badtuxx/DescomplicandoKubernetes#14]

**Comment by P0ssuidao** [comment]
Vou começar preparar aqui.

**Comment by P0ssuidao** [comment]
@badtuxx sobre o conteúdo prefere que abra o pr com ele completo ou pode ir indo por partes ?

**Comment by badtuxx** [comment]
Pode ser por partes, sem problemas, cria um diretório e manda ver.. :D

**Comment by P0ssuidao** [comment]
Showw vou escrever mais um pouco nessa primeira parte aqui mais tarde já  abro o PR.
