### ISSUE TITLE
Utilização de lint para markdown

### ISSUE THREAD

**Issue by afonsoaugusto** [badtuxx/DescomplicandoKubernetes#2]
Como a documentação está sendo escrita em Markdown seria legal utilizar um lint.
Eu utilizo o plugin [davidanson.vscode-markdownlint](https://github.com/DavidAnson/vscode-markdownlint.git).

![markdown-link](https://user-images.githubusercontent.com/2923610/81600872-b0e3f000-93a0-11ea-84da-9c00952029df.png)

É uma sugestão a utilização dele para formatar o markdown.
Abaixo uma imagem com exemplos de Warnings:

![markdown-issue](https://user-images.githubusercontent.com/2923610/81600859-ac1f3c00-93a0-11ea-8155-4e8bbb4eb0f9.png)

**Comment by aeciopires** [comment]
@afonsoaugusto estou usando este link e também o plugin: 
* https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc

**Comment by aeciopires** [comment]
@afonsoaugusto já adicionei a dica de uso do VSCode e plugins nesse PR: https://github.com/badtuxx/DescomplicandoKubernetes/pull/43

**Comment by afonsoaugusto** [comment]
Show demais @aeciopires , vou fechar a issue.
