### ISSUE TITLE
Adicionar simulado para os exames

### ISSUE THREAD

**Issue by marcelofreire1988** [badtuxx/DescomplicandoKubernetes#33]
Olá @badtuxx , o que acha que criar um simulado para o pessoal que deseja se preparar para os exames?
Poderíamos dividir em simulados para a cka e ckad.

**Comment by badtuxx** [comment]
Podemos abrir o que tem na plataforma tbm! Acho foda!

**Comment by marcelofreire1988** [comment]
Se quiser, posso inventar alguns também!

Seria massa depois , gravar as resoluções dos exercícios.  

Ai fica aberto a quem quiser responder e publicar no youtube, etc.

**Comment by badtuxx** [comment]
Sensacional!

**Comment by SpawW** [comment]
muuuito interessado ! posso ser beta das questões ? :D

**Comment by marcelofreire1988** [comment]
Vou ver se consigo criar algumas questões e pesquisar algumas outras em outros repos que existem e agrupar-los aqui.

**Comment by SpawW** [comment]
Sugestões de temas de questão a partir do day-2:
- Session Affinity
