### ISSUE TITLE
Conteúdo em HTML (Website)

### ISSUE THREAD

**Issue by rcjeferson** [badtuxx/DescomplicandoKubernetes#49]
Utilizar algum framework como o [VuePress](https://vuepress.vuejs.org/) para gerar o conteúdo da documentação em HTML, permitindo a criação de uma interface mais amigável, com melhor indexação e buscas do conteúdo. Ex.: https://starship.rs/

Com o conteúdo em HTML, é possível hospedar em qualquer plataforma (como o [Netlify](https://www.netlify.com/)) e usar algum domínio (como [descomplicandok8s.com.br](https://registro.br/busca-dominio?fqdn=descomplicandok8s.com.br)) para transformar o conteúdo em um website.

Além disso, o [VuePress](https://vuepress.vuejs.org/) possui recursos de internacionalização, sendo possível adicionar vários idiomas e permitindo o usuário selecionar o de sua preferência (como no [Starship](https://starship.rs/)) .

Abaixo, um exemplo gerado com o próprio projeto.

![image](https://user-images.githubusercontent.com/43759952/82737178-57b37f00-9d05-11ea-9a21-18546bb43030.png)

**Comment by rcjeferson** [comment]
@badtuxx o que acha?

Posso trabalhar nisso se achar uma boa.

**Comment by willdevsp** [comment]
dependendo da pra hospedar no proprio github.io  ficaria descomplicandokubernetes.github.io
Segue um exemplo de um amigo. http://rgoncalves94.github.io/jtcgen/

**Comment by rcjeferson** [comment]
Sim, o GitHub Pages também é uma boa, mas usar um domínio próprio acho que seria interessante, pois caso seja necessário mudar a hospedagem, podemos fazer isso sem ter que trocar a URL.

Dá para configurar URLs personalizadas no GitHub Pages também, então daria para usar sem problemas.

**Comment by badtuxx** [comment]
Estava pensando em subir o conteúdo no site da LINUXtips, assim ficaria mais fácil no futuro adicionar o material escrito com os vídeos. :)
Vou preparar algo por lá, o que acham?

**Comment by willdevsp** [comment]
boa!

**Comment by rcjeferson** [comment]
Boa!

Se precisar de alguma força, estamos ai!
